; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = NASA Clipper Duet Echo Sounder/Log to NMEA2000 converter

[env]
platform = espressif32@^4.0.0
framework = arduino
board = esp32dev
lib_ldf_mode = deep
board_build.partitions = partitions_custom.csv
extra_scripts = 
	pre:version.py
lib_deps = 
	ayushsharma82/ElegantOTA@^3.1.6
	ttlappalainen/NMEA2000-library@^4.22.0
	ttlappalainen/NMEA2000_esp32@^1.0.3
	ttlappalainen/NMEA0183@^1.10.1

[env:esp32dev]
monitor_speed = 115200
build_flags = 
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env:esp32dev-nmea0183]
monitor_speed = 4800
build_flags = 
	-D NMEA0183_FIRST=1
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

