; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = NASA Clipper Duet Echo Sounder/Log to NMEA2000 and Signal K converter
default_envs = esp32devkitv1

[env]
platform = espressif32@^6.0.0
framework = arduino
board = esp32doit-devkit-v1
lib_ldf_mode = deep+
board_build.partitions = partitions_custom.csv
build_unflags =
	-std=gnu++11
build_flags =
	-std=gnu++17
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
extra_scripts = 
	pre:version.py
lib_deps = 
	SignalK/SensESP@^3.0.0
	ttlappalainen/NMEA2000-library@^4.22.0
	ttlappalainen/NMEA2000_esp32@^1.0.3
	ttlappalainen/NMEA0183@^1.10.1

[env:esp32devkitv1]
monitor_speed = 115200

